apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: dotnet_app
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: dotnet_app
    tier: frontend
